Link libpthread
gcc -o test-zeroconf test-zeroconf.c -O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic  -D_REENTRANT  -I/usr/include/libxml2  -I/usr/include/p11-kit-1    -I/usr/include/libpng16 -fPIC objs//libairscan.a  -lavahi-common -lavahi-client  -lxml2  -lgnutls -lm -fPIE  -ljpeg  -lpng16 -lz
/usr/bin/x86_64-openmandriva-linux-gnu-ld: objs//libairscan.a(airscan-eloop.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/bin/x86_64-openmandriva-linux-gnu-ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line